---
logging:
  level:
    root: info

server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost/pdf_manager
    username: dbadmin
    password: XXXXXXXXXXXXXXXXXXX
  devtools:
    livereload:
      enabled: true
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 12Mb
  jackson:
    serialization:
      indent_output: true
  jpa:
    generate-ddl: true

